# Nama workflow yang akan muncul di tab Actions GitHub
name: Generate ConnectSphere ZK Proof

# Pemicu (trigger) workflow
on:
  # 'workflow_dispatch' memungkinkan kita menjalankan workflow ini secara manual
  workflow_dispatch:
    # Definisikan input yang akan diminta dari pengguna
    inputs:
      secret_a:
        description: 'Your first secret number (e.g., 12345)'
        required: true
        type: string
      secret_b:
        description: 'Your second secret number (e.g., 67890)'
        required: true
        type: string

jobs:
  generate-proof:
    # Gunakan runner Ubuntu terbaru dari GitHub
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode repositori Anda ke dalam runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Siapkan environment Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Langkah 3: Install SP1 Toolchain secara manual
      - name: Install SP1 Toolchain
        run: |
          echo "Cloning SP1 repository..."
          git clone https://github.com/succinctlabs/sp1.git ~/sp1
          
          echo "Installing SP1 CLI..."
          cd ~/sp1/crates/cli
          cargo install --path .

          # --- PERBAIKAN DI SINI ---
          # Secara eksplisit tambahkan direktori bin Cargo ke PATH untuk sesi ini
          export PATH="$HOME/.cargo/bin:$PATH"

          echo "Verifying cargo prove installation..."
          cargo prove --version

          echo "Manually linking SP1 toolchain..."
          sp1up
          mkdir -p ~/.sp1/toolchains/succinct
          tar -xvf ~/.sp1/rust-toolchain-x86_64-unknown-linux-gnu.tar.gz -C ~/.sp1/toolchains/succinct --strip-components=1
          rustup toolchain link succinct ~/.sp1/toolchains/succinct
          
          # Kembali ke direktori kerja utama
          cd $GITHUB_WORKSPACE

      # Langkah 4: Hitung nilai 'n' dari input rahasia pengguna
      - name: Calculate N
        id: calculate_n
        run: |
          a=${{ inputs.secret_a }}
          b=${{ inputs.secret_b }}
          n=$((a * b))
          echo "n_value=$n" >> $GITHUB_OUTPUT

      # Langkah 5: Jalankan Prover Script dengan input dari pengguna
      - name: Run ZK Prover
        run: |
          echo "Starting ZK proof generation for n=${{ steps.calculate_n.outputs.n_value }}..."
          cargo run --release -p proof-of-secret-script -- --n ${{ steps.calculate_n.outputs.n_value }} --a ${{ inputs.secret_a }} --b ${{ inputs.secret_b }}
        timeout-minutes: 30

      # Langkah 6: Jalankan Converter Script untuk mendapatkan output final
      - name: Convert Proof to Sui Arguments
        run: |
          echo "Converting proof and printing arguments..."
          cargo run --release -p proof-converter-script
