# Nama workflow yang akan muncul di tab Actions GitHub
name: Generate ConnectSphere ZK Proof

on:
  # 'workflow_dispatch' memungkinkan kita menjalankan workflow ini secara manual
  workflow_dispatch:
    inputs:
      secret_a:
        description: 'Your first secret number (e.g., 12345)'
        required: true
        type: string
      secret_b:
        description: 'Your second secret number (e.g., 67890)'
        required: true
        type: string

jobs:
  generate-proof:
    # Gunakan runner Ubuntu terbaru dari GitHub
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode repositori Anda
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Langkah 2: Instal Rust
      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      # Langkah 3: Instal SP1 Toolchain (Metode Resmi yang Benar)
      - name: Install SP1 Toolchain using sp1up
        run: |
          # Tambahkan direktori bin Cargo ke PATH untuk sesi ini
          source "$HOME/.cargo/env"
          
          # Jalankan installer resmi sp1up
          curl -L https://sp1up.succinct.xyz | bash
          
          # Installer memodifikasi .bashrc, jadi kita source lagi untuk membuat sp1up tersedia
          source "$HOME/.bashrc"
          
          # Jalankan sp1up untuk menginstal toolchain (prover & succinct)
          sp1up
          
          # Verifikasi instalasi untuk memastikan semuanya siap
          echo "Verifying installations..."
          cargo prove --version
          cargo +succinct --version
      
      # Langkah 4: Hitung nilai 'n' dari input rahasia pengguna
      - name: Calculate N
        id: calculate_n
        run: |
          a=${{ inputs.secret_a }}
          b=${{ inputs.secret_b }}
          n=$((a * b))
          echo "n_value=$n" >> $GITHUB_OUTPUT

      # Langkah 5: Jalankan Prover Script dengan input dari pengguna
      - name: Run ZK Prover
        # Tambahkan `shell: bash` untuk memastikan perintah source berfungsi dengan benar
        shell: bash
        run: |
          # Pastikan PATH sudah benar sebelum menjalankan cargo
          source "$HOME/.cargo/env"
          source "$HOME/.bashrc"
          
          echo "Starting ZK proof generation for n=${{ steps.calculate_n.outputs.n_value }}..."
          cargo run --release -p proof-of-secret-script -- --n ${{ steps.calculate_n.outputs.n_value }} --a ${{ inputs.secret_a }} --b ${{ inputs.secret_b }}
        timeout-minutes: 30

      # Langkah 6: Jalankan Converter Script untuk mendapatkan output final
      - name: Convert Proof to Sui Arguments
        shell: bash
        run: |
          # Pastikan PATH sudah benar sebelum menjalankan cargo
          source "$HOME/.cargo/env"
          source "$HOME/.bashrc"
          
          echo "Converting proof and printing arguments..."
          cargo run --release -p proof-converter-script
